version: '3.7'

services:
  testephp-app:
    build: .
    container_name: testephp-app
    entrypoint: sh cmd.sh
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:80"
    depends_on:
      - testephp-db
    networks:
      - testephp-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: testephp-db
      DB_PORT: 3306
      DB_DATABASE: testephp
      DB_USERNAME: root
      DB_PASSWORD: root

  testephp-db:
    image: mysql:5.7
    container_name: testephp-db
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testephp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - testephp-network

networks:
  testephp-network:
    driver: bridge